name: Publish_Mac

on:
  release:
    types: [published]

jobs:

  publish_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: tags/${GITHUB_REF}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - name: Build release
        run: mvn -B -DskipTests package --file pom.xml
      - name: Stage release
        run: mkdir staging && cp target/AnsibleVaultFX*.dmg staging
      - name: Publish release
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

  publish_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: tags/${GITHUB_REF}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - name: Build release
        run: mvn -B -DskipTests package --file pom.xml
      - name: Stage release
        run: mkdir staging && cp target/ansible-vault-fx*.jar staging
      - name: Publish release
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

  publish_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: tags/${GITHUB_REF}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - name: Build release
        run: mvn -B -DskipTests package --file pom.xml
      - name: Stage release
        run: mkdir staging && cp target/ansible-vault-fx*.jar staging
      - name: Publish release
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
