name: Release

on: [workflow_dispatch]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode release:prepare -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN
      - name: Search for properties
        run: echo "${GITHUB_WORKSPACE}" && find ${GITHUB_WORKSPACE} -name "release.properties" -print -exec cat -n {} \;
      - name: Upload relese properties
        uses: actions/upload-artifact@v2
        with:
          name: release-properties
          path: /home/runner/work/AnsibleVaultFx/AnsibleVaultFx/release.properties

  publish_macos:
    runs-on: macos-latest
    needs: release
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Download release properties
        uses: actions/download-artifact@v2
        with:
          name: release-properties
      - name: Search for properties
        run: echo "${GITHUB_WORKSPACE}" && find ${GITHUB_WORKSPACE} -name "release.properties" -exec cat -n {} \;
      - name: Perform release for MacOs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode -Darguments="-Dmaven.javadoc.skip=true" release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN
      - name: Stage release
        run: mkdir staging && cp target/checkout/target/AnsibleVaultFX*.dmg staging
      - name: List workspace and current dir
        run: ls -ltr ${GITHUB_WORKSPACE} && pwd && ls -ltr
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["${GITHUB_WORKSPACE}/staging/*.dmg"]'
  publish_linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Configure git
        run: |
          git config --global committer.email "noreply@github.com"
          git config --global committer.name "GitHub"
          git config --global author.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global author.name "${GITHUB_ACTOR}"
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Download release properties
        uses: actions/download-artifact@v2
        with:
          name: release-properties
      - name: Search for properties
        run: echo "${GITHUB_WORKSPACE}" && find ${GITHUB_WORKSPACE} -name "release.properties" -print
      - name : Perform release for Linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode -Darguments="-Dmaven.javadoc.skip=true" release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN
      - name: List binaries
        run: ls -ltr ${GITHUB_WORKSPACE}/target/checkout/target
      - name: Stage release
        run: mkdir staging && cp target/checkout/target/*linux.jar staging
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["staging/*linux.jar"]'
  publish_windows:
    runs-on: windows-latest
    needs: release
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Download release properties
        uses: actions/download-artifact@v2
        with:
          name: release-properties
      - name: Perform release for Windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn --batch-mode -Darguments="-Dmaven.javadoc.skip=true" release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN
      - name: Stage release
        run: mkdir staging && copy target\checkout\target\*win.jar staging
      - name: Upload release binaries
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./staging/*win.jar"]'